release-version:
  stage: deploy
  image: node:22
  script:
    - git config --global user.email "${GIT_CI_EMAIL}"
    - git config --global user.name "${GIT_CI_USER}"
    - npm i standard-version --location=global
    - npm run release -- --no-verify
    - git remote set-url --push origin https://$GIT_CI_USER:$GIT_CI_PASSWORD@gitlab.com/$CI_PROJECT_PATH.git
    - git push --follow-tags origin HEAD:$CI_COMMIT_REF_NAME
  rules:
    - if: $CI_COMMIT_BRANCH == "main" && $CI_COMMIT_TITLE !~ /^chore\(release\).*\ \[release\]$/

publish:
  stage: deploy
  image: node:22
  script:
    - npm config set @tldx:registry=https://gitlab.com/api/v4/packages/npm/
    - npm config set -- '//gitlab.com/api/v4/packages/npm/:_authToken'="${CI_JOB_TOKEN}"
    - npm config set -- '//gitlab.com/api/v4/projects/${CI_PROJECT_ID}/packages/npm/:_authToken'="${CI_JOB_TOKEN}"
    - npm ci
    - npm run test
    - npm run build
    - npm publish
    - echo "-- build completed succesfully"
  rules:
    - if: $CI_COMMIT_TAG && $CI_COMMIT_TAG =~ /^v?[0-9]+\.[0-9]+\.[0-9]+$/

